# Server config
server:
  port: 8080

# Spring config
spring:
  application:
    name: article-service
  logging:
    level:
      org.springframework: WARN
      org.hibernate: WARN

# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: http://${LOCAL_HOST}:8761/eureka/

# Ribbon config
ribbon:
  eureka:
    enabled: true
