# Server config
server:
  port: 8761

# Spring config
spring:
  application:
    name: discovery-service

# Eureka config
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${LOCAL_HOST}:8761/eureka/
